name: Build

on:
  workflow_call:
    inputs:
      ballerina-bot-username:
        required: true
        type: string
      ballerina-bot-token:
        required: true
        type: string
      additional-build-flags:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Change to Timestamped Version
        run: |
          startTime=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M00')
          latestCommit=$(git log -n 1 --pretty=format:"%h")
          VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)
          updatedVersion=$VERSION-$startTime-$latestCommit
          echo $updatedVersion
          sed -i "s/version=\(.*\)/version=$updatedVersion/g" gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          packageUser: ${{ inputs.ballerina-bot-username }}
          packagePAT: ${{ inputs.ballerina-bot-token }}
          publishUser: ${{ inputs.ballerina-bot-username }}
          publishPAT: ${{ inputs.ballerina-bot-token}}
        run: ./gradlew publish --no-daemon --scan ${{ inputs.additional-build-flags }}

      - name: Generate CodeCov Report
        uses: codecov/codecov-action@v3
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ballerina-runtime
          path: target/ballerina-runtime/
