name: Publish to the Ballerina central

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ballerina-bot-username:
        required: true
        type: string
      ballerina-bot-token:
        required: true
        type: string
      additional-build-flags:
        required: false
        type: string
        default: ''
      additional-publish-flags:
        required: false
        type: string
        default: ''
      ballerina-central-dev-access-token:
        required: false
        type: string
        default: ''
      ballerina-central-stage-access-token:
        required: false
        type: string
        default: ''

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -x check -x test ${{ inputs.additional-build-flags }}

      - name: Create lib directory if not exists
        run: mkdir -p ballerina/lib

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "rootfs"
          scan-ref: "/github/workspace/ballerina/lib"
          format: "table"
          timeout: "10m0s"
          exit-code: "1"

      - name: Ballerina Central Dev Push
        if: ${{ inputs.environment == 'DEV CENTRAL' }}
        env:
          BALLERINA_DEV_CENTRAL: true
          BALLERINA_STAGE_CENTRAL: false
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ inputs.ballerina-central-dev-access-token }}
          packageUser: ${{ inputs.ballerina-bot-username }}
          packagePAT: ${{ inputs.ballerina-bot-token }}
          GITHUB_TOKEN: ${{ inputs.ballerina-bot-token }}
        run: |
          sed -i 's/version=\(.*\)-SNAPSHOT/version=\1/g' gradle.properties
          ./gradlew clean build -PpublishToCentral=true ${{ inputs.additional-publish-flags }}

      - name: Ballerina Central Stage Push
        if: ${{ inputs.environment == 'STAGE CENTRAL' }}
        env:
          BALLERINA_DEV_CENTRAL: false
          BALLERINA_STAGE_CENTRAL: true
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ inputs.ballerina-central-stage-access-token }}
          packageUser: ${{ inputs.ballerina-bot-username }}
          packagePAT: ${{ inputs.ballerina-bot-token }}
          GITHUB_TOKEN: ${{ inputs.ballerina-bot-token }}
        run: |
          sed -i 's/version=\(.*\)-SNAPSHOT/version=\1/g' gradle.properties
          ./gradlew clean build -PpublishToCentral=true ${{ inputs.additional-publish-flags }}
